/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kvlxd.ui;

import com.kvlxd.dao.HoaDonNhapChiTietDAO;
import com.kvlxd.dao.HoaDonNhapDAO;
import com.kvlxd.dao.KhoDAO;
import com.kvlxd.dao.MatHangDAO;
import com.kvlxd.dao.NhaCungCapDAO;
import com.kvlxd.dao.NhanVienDAO;
import com.kvlxd.dao.ThongKeDAO;
import com.kvlxd.entity.HoaDonNhap;
import com.kvlxd.entity.HoaDonNhapChiTiet;
import com.kvlxd.entity.Kho;
import com.kvlxd.entity.MatHang;
import com.kvlxd.entity.NhaCungCap;
import com.kvlxd.entity.NhanVien;
import com.kvlxd.util.Auth;
import com.kvlxd.util.CheckData;
import com.kvlxd.util.MsgBox;
import com.kvlxd.util.WFile;
import com.kvlxd.util.XDate;
import java.awt.event.WindowAdapter;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.file.Path;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import org.apache.poi.openxml4j.exceptions.InvalidFormatException;

import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author ADMIN
 */
public class HoaDonNhapJDialog extends javax.swing.JInternalFrame {

    public HoaDonNhapJDialog(java.awt.Frame parent, boolean modal) {
        //super(parent, modal);
        initComponents();
        // setLocationRelativeTo(null);
        this.setSize(1920, 1080);

    }
    int row = 0;
    int check = 0;
    NhanVienDAO daonv = new NhanVienDAO();
    KhoDAO daoKho = new KhoDAO();
    NhaCungCapDAO daoNCC = new NhaCungCapDAO();
    MatHangDAO daoMatHang = new MatHangDAO();
    HoaDonNhapDAO daoHDN = new HoaDonNhapDAO();
    HoaDonNhapChiTietDAO daoHDNCT = new HoaDonNhapChiTietDAO();
    ThongKeDAO daoThongKe = new ThongKeDAO();
    List<MatHang> list = new ArrayList<>();
    List<HoaDonNhap> listHDN = new ArrayList<>();
    List<HoaDonNhapChiTiet> listHDCT = new ArrayList<>();
    List<HoaDonNhapChiTiet> listCT = new ArrayList<>();

    HoaDonNhapJDialog() {
        initComponents();
        // setLocationRelativeTo(null);
        AutoCompleteDecorator.decorate(cboTenNCC);
        AutoCompleteDecorator.decorate(cboLocTheoMaHD);
        AutoCompleteDecorator.decorate(cboTenMatHang);
        AutoCompleteDecorator.decorate(cboKho);
        fillCboKho();
        fillCboTenNCC();
        fillCboDVT();
        fillCboMaHD();
        clearForm();
//        TongSLMatHang();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tabs = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaHDN = new javax.swing.JTextField();
        txtTenNV = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtSDTNCC = new javax.swing.JTextField();
        txtDiaChiNCC = new javax.swing.JTextField();
        txtTenLxe = new javax.swing.JTextField();
        txtSDTLxe = new javax.swing.JTextField();
        cboTenNCC = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtNgayNhap = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblDVT = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMatHang = new javax.swing.JTable();
        btnMoiMatHang = new javax.swing.JButton();
        btnThemMatHang = new javax.swing.JButton();
        btnSuaMatHang = new javax.swing.JButton();
        btnXoaMatHang = new javax.swing.JButton();
        cboTenMatHang = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        cboKho = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        btnExportMatHangCT = new javax.swing.JButton();
        btnImport = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        lblTongTienHDN = new javax.swing.JLabel();
        lblTongTienHDN1 = new javax.swing.JLabel();
        btnMoi = new javax.swing.JButton();
        btnThemHD = new javax.swing.JButton();
        btnSuaHD = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtTimTheoNgay = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cboLocTheoMaHD = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDanhSachHDN = new javax.swing.JTable();
        btnTim = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Ngày nhập :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Mã HĐN :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Tên nhân viên :");

        txtMaHDN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtTenNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("SDT - NCC :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Tên nhà cung cấp :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Địa chỉ NCC :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Tên lái xe :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("SĐT lái xe");

        txtSDTNCC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtDiaChiNCC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtTenLxe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtSDTLxe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cboTenNCC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboTenNCC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Xi", "Măng", "Cát", "Sỏi", " " }));
        cboTenNCC.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboTenNCCItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboTenNCC, 0, 291, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSDTNCC, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                            .addComponent(txtDiaChiNCC))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTenLxe, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSDTLxe, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTenLxe, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboTenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSDTNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSDTLxe, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiaChiNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Thông tin nhà cung cấp :");

        txtNgayNhap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNgayNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayNhapActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Danh sách mặt hàng :");

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Số lượng :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Tên mặt hàng :");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Đơn giá :");

        lblDVT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDVT.setText("ĐVT");

        txtSoLuong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtGia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tblMatHang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblMatHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã MH", "Tên MH", "ĐVT", "Số lượng", "Đơn giá", "Thành tiền", "Ghi chú"
            }
        ));
        tblMatHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMatHangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblMatHang);

        btnMoiMatHang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMoiMatHang.setText("Mới");
        btnMoiMatHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiMatHangActionPerformed(evt);
            }
        });

        btnThemMatHang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThemMatHang.setText("Thêm MH");
        btnThemMatHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMatHangActionPerformed(evt);
            }
        });

        btnSuaMatHang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSuaMatHang.setText("Sửa MH");
        btnSuaMatHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaMatHangActionPerformed(evt);
            }
        });

        btnXoaMatHang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnXoaMatHang.setText("Xóa MH");
        btnXoaMatHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaMatHangActionPerformed(evt);
            }
        });

        cboTenMatHang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboTenMatHang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Xi", "Măng", "Cát", "Sỏi", " " }));
        cboTenMatHang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboTenMatHangItemStateChanged(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Kho :");

        cboKho.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboKho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Xi", "Măng", "Cát", "Sỏi", " " }));
        cboKho.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboKhoItemStateChanged(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Ghi chú :");

        txtGhiChu.setColumns(20);
        txtGhiChu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtGhiChu.setRows(5);
        jScrollPane1.setViewportView(txtGhiChu);

        btnExportMatHangCT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExportMatHangCT.setText("Export ");
        btnExportMatHangCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportMatHangCTActionPerformed(evt);
            }
        });

        btnImport.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnImport.setText("Import ");
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("VND");

        lblTongTienHDN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTongTienHDN.setText("VND");

        lblTongTienHDN1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTongTienHDN1.setText("Tổng tiền :");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(83, 83, 83)
                        .addComponent(cboKho, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                    .addComponent(txtGia))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDVT, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)))
                            .addComponent(cboTenMatHang, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnMoiMatHang, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnThemMatHang)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnImport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSuaMatHang, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnXoaMatHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExportMatHangCT))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTongTienHDN1)
                        .addGap(18, 18, 18)
                        .addComponent(lblTongTienHDN, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTongTienHDN, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTongTienHDN1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMoiMatHang)
                            .addComponent(btnThemMatHang)
                            .addComponent(btnSuaMatHang)
                            .addComponent(btnXoaMatHang))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnExportMatHangCT)
                            .addComponent(btnImport))
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboKho, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboTenMatHang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDVT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14))
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))))
        );

        btnMoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMoi.setText("Mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        btnThemHD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThemHD.setText("Thêm HĐ");
        btnThemHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemHDActionPerformed(evt);
            }
        });

        btnSuaHD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSuaHD.setText("Sửa HĐ");
        btnSuaHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaHDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(337, 337, 337)
                .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnThemHD, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnSuaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(txtMaHDN, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(123, 123, 123)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel10)))
                        .addGap(157, 253, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(0, 859, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaHDN, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMoi)
                    .addComponent(btnThemHD)
                    .addComponent(btnSuaHD))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        tabs.addTab("Thông tin chi tiết HDN", jPanel3);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Tìm kiếm theo ngày :");

        txtTimTheoNgay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Tìm kiếm theo MaHĐ :");

        cboLocTheoMaHD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboLocTheoMaHD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboLocTheoMaHD.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboLocTheoMaHDItemStateChanged(evt);
            }
        });
        cboLocTheoMaHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboLocTheoMaHDMouseClicked(evt);
            }
        });
        cboLocTheoMaHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLocTheoMaHDActionPerformed(evt);
            }
        });
        cboLocTheoMaHD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboLocTheoMaHDKeyPressed(evt);
            }
        });

        tblDanhSachHDN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblDanhSachHDN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã HĐN", "Mã NV", "Tên nhà cung cấp", "Tên lái xe", "SĐT lái xe", "Ngày nhập"
            }
        ));
        tblDanhSachHDN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachHDNMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblDanhSachHDN);

        btnTim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTimTheoNgay)
                    .addComponent(cboLocTheoMaHD, 0, 242, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnTim)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1025, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTimTheoNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTim)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(cboLocTheoMaHD))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        tabs.addTab("Danh sách hóa đơn nhập", jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 1040, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabs))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuaMatHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaMatHangActionPerformed
        updateMatHang();

    }//GEN-LAST:event_btnSuaMatHangActionPerformed

    private void txtNgayNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayNhapActionPerformed

    private void cboTenNCCItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboTenNCCItemStateChanged
        if (cboTenNCC.getSelectedItem() != null) {
            fillNCC();
        }
    }//GEN-LAST:event_cboTenNCCItemStateChanged

    private void cboTenMatHangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboTenMatHangItemStateChanged
        // TODO add your handling code here:
        fillCboDVT();
    }//GEN-LAST:event_cboTenMatHangItemStateChanged

    private void cboKhoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboKhoItemStateChanged
        if (cboKho.getSelectedItem() != null) {
            fillCboMatHang();
        }
    }//GEN-LAST:event_cboKhoItemStateChanged

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        clearForm();

    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnMoiMatHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiMatHangActionPerformed
        clearMatHangMoi();
    }//GEN-LAST:event_btnMoiMatHangActionPerformed

    private void btnThemMatHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMatHangActionPerformed
        String err = checkCT("Them");
        if (err.equals("")) {
            HoaDonNhap hd = daoHDN.selectById(txtMaHDN.getText());
            if (hd == null) {
                InsertMatHang();
            } else {
                List<HoaDonNhapChiTiet> li = daoHDNCT.selectByIdd(Integer.parseInt(txtMaHDN.getText()));
                if (li.size() >= 1) {
                    HoaDonNhapChiTiet hdct = li.get(0);
                    if (hdct != null) {
                        listHDCT.clear();
                        InsertMatHang();
                        insertHDNCT();
                        fillTableMatHang1();
                        
                    } else {
                        InsertMatHang2();
                        fillTableMatHang2();

                    }
                }
            }
        } else {
            MsgBox.alert(this, err);
        }
        
    }//GEN-LAST:event_btnThemMatHangActionPerformed

    private void btnXoaMatHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaMatHangActionPerformed
        deleteMatHang();

    }//GEN-LAST:event_btnXoaMatHangActionPerformed

    private void tblMatHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMatHangMouseClicked
        if (evt.getClickCount() == 1) {
            editMatHang();
        }
    }//GEN-LAST:event_tblMatHangMouseClicked

    private void btnThemHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemHDActionPerformed
        insertHDN();
        insertHDNCT();
//        TongSLMatHang();
        clearForm();
    }//GEN-LAST:event_btnThemHDActionPerformed

    private void tblDanhSachHDNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachHDNMouseClicked
        if (evt.getClickCount() == 1) {
            this.row = tblDanhSachHDN.getSelectedRow();
            this.editDanhSachHDN();
        }
        try {
            fillDSHoaDonChiTiet();
        } catch (Exception e) {
            MsgBox.alert(this, "Đơn nhập không có sản phẩm");
        }

    }//GEN-LAST:event_tblDanhSachHDNMouseClicked

    private void btnSuaHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaHDActionPerformed
        updateHDN();
//        TongSLMatHang();
        //updateHDNCT();
    }//GEN-LAST:event_btnSuaHDActionPerformed

    private void cboLocTheoMaHDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboLocTheoMaHDItemStateChanged

        if (cboLocTheoMaHD.getItemCount() > 0) {
            if (cboLocTheoMaHD.getSelectedItem().equals("...")) {
                fillTableHDN();
            } else {
                fillTableTheoMaHD();
            }
        }

    }//GEN-LAST:event_cboLocTheoMaHDItemStateChanged

    private void cboLocTheoMaHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboLocTheoMaHDMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cboLocTheoMaHDMouseClicked

    private void cboLocTheoMaHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLocTheoMaHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboLocTheoMaHDActionPerformed

    private void cboLocTheoMaHDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboLocTheoMaHDKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboLocTheoMaHDKeyPressed

    private void btnExportMatHangCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportMatHangCTActionPerformed
        if (listHDCT.isEmpty()) {
            MsgBox.alert(this, "Chưa có mặt hàng");
        } else {
            ExportExcel(createNewFile());
        }
    }//GEN-LAST:event_btnExportMatHangCTActionPerformed

    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportActionPerformed

        importExcel();
        check = -1;

    }//GEN-LAST:event_btnImportActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        timHDNTheoNgay();
    }//GEN-LAST:event_btnTimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoaDonNhapJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoaDonNhapJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoaDonNhapJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoaDonNhapJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HoaDonNhapJDialog dialog = new HoaDonNhapJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportMatHangCT;
    private javax.swing.JButton btnImport;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnMoiMatHang;
    private javax.swing.JButton btnSuaHD;
    private javax.swing.JButton btnSuaMatHang;
    private javax.swing.JButton btnThemHD;
    private javax.swing.JButton btnThemMatHang;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoaMatHang;
    private javax.swing.JComboBox<String> cboKho;
    private javax.swing.JComboBox<String> cboLocTheoMaHD;
    private javax.swing.JComboBox<String> cboTenMatHang;
    private javax.swing.JComboBox<String> cboTenNCC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblDVT;
    private javax.swing.JLabel lblTongTienHDN;
    private javax.swing.JLabel lblTongTienHDN1;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tblDanhSachHDN;
    private javax.swing.JTable tblMatHang;
    private javax.swing.JTextField txtDiaChiNCC;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMaHDN;
    private javax.swing.JTextField txtNgayNhap;
    private javax.swing.JTextField txtSDTLxe;
    private javax.swing.JTextField txtSDTNCC;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenLxe;
    private javax.swing.JTextField txtTenNV;
    private javax.swing.JTextField txtTimTheoNgay;
    // End of variables declaration//GEN-END:variables
    private void addWindowListener(WindowAdapter windowAdapter) {

    }

    HoaDonNhap getFormTO() {
        HoaDonNhap hdn = new HoaDonNhap();
//        hdn.setMaHDN(Integer.parseInt(txtMaHDN.getText()));

        hdn.setMaNV(Auth.user.getMaNV());

        NhaCungCap ncc = daoNCC.selectBySDTNCC(cboTenNCC.getSelectedItem() + "");
        String MaNcc = ncc.getMaNCC();
        hdn.setMaNCC(MaNcc);
        hdn.setSDTLaiXe(txtSDTLxe.getText());
        hdn.setTenLaiXe(txtTenLxe.getText());
        java.util.Date utilDate = XDate.toDate(txtNgayNhap.getText(), "yyyy-MM-dd");
        hdn.setNgayNhap(new java.sql.Date(utilDate.getTime()));
        return hdn;
    }

    HoaDonNhap getFormTO2() {
        HoaDonNhap hdn = new HoaDonNhap();
        hdn.setMaNV(Auth.user.getMaNV());
        NhaCungCap ncc = daoNCC.selectBySDTNCC(cboTenNCC.getSelectedItem() + "");
        String MaNcc = ncc.getMaNCC();
        hdn.setMaNCC(MaNcc);
        hdn.setSDTLaiXe(txtSDTLxe.getText());
        hdn.setTenLaiXe(txtTenLxe.getText());
        java.util.Date utilDate = XDate.toDate(txtNgayNhap.getText(), "yyyy-MM-dd");
        hdn.setNgayNhap(new java.sql.Date(utilDate.getTime()));
        hdn.setMaHDN(Integer.parseInt(txtMaHDN.getText()));
        return hdn;
    }

    void setFormTO(HoaDonNhap hdn) {
        // row = tblDanhSachHDN.getSelectedRow();
        NhanVien nv = daonv.selectByTenNV(hdn.getMaNV());
        String tennv = nv.getTenNV();
        txtMaHDN.setText(String.valueOf(hdn.getMaHDN()));

        txtNgayNhap.setText(XDate.toString2(hdn.getNgayNhap(), "yyyy-MM-dd"));
        txtTenNV.setText(tennv);

        NhaCungCap ncc = daoNCC.selectById(hdn.getMaNCC());
        String tenNCC = ncc.getTenNCC();
        cboTenNCC.setSelectedItem(tenNCC);
        txtTenLxe.setText(hdn.getTenLaiXe());
        txtSDTLxe.setText(hdn.getSDTLaiXe());

    }

    private void insertHDN() {
        String err = check("Them");
        if (err.equals("")) {
            if (listHDCT.isEmpty()) {
                MsgBox.alert(this, "Bạn chưa thêm mặt hàng ");

            } else {
                HoaDonNhap hdn = getFormTO();

                try {
                    daoHDN.insert(hdn);
                    fillTableHDN();
                    MsgBox.alert(this, "Thêm hóa đơn nhập thành công!");
                } catch (Exception e) {
                    MsgBox.alert(this, "Thêm hóa đơn nhập thất bại");
                    e.printStackTrace();
                }
            }

        } else {
            MsgBox.alert(this, err);

        }
    }

    private void insertHDNCT() {
        if (txtMaHDN.getText().equals("")) {
            MsgBox.alert(this, "Chưa có hóa đơn nhập");
        }
        for (HoaDonNhapChiTiet hdct : listHDCT) {
            daoHDNCT.insert(hdct);
            updateSLMatHang(daoMatHang.selectById(hdct.getMaMH()));
            fillTableMatHang();
        }
    }

    private void updateHDN() {
        String err = check("Sua");
        if (err.equals("")) {
            HoaDonNhap hdn = getFormTO2();
            try {
                daoHDN.update(hdn);
                
                fillTableHDN();
                clearForm();
                MsgBox.alert(this, "Sửa hóa đơn nhập thành công!");
            } catch (Exception e) {
                e.printStackTrace();
                MsgBox.alert(this, "Sửa hóa đơn nhập thất bại");
            }
        } else {
            MsgBox.alert(this, err);

        }
    }

    private void fillTableHDN() {
        DefaultTableModel model = (DefaultTableModel) tblDanhSachHDN.getModel();
        model.setRowCount(0);
        List<HoaDonNhap> list = daoHDN.selectAll();
        String tenncc = "";

        try {
            for (HoaDonNhap hdn : list) {
                NhaCungCap listNCC = daoNCC.selectById(hdn.getMaNCC());
                tenncc = listNCC.getTenNCC();
                model.addRow(new Object[]{hdn.getMaHDN(), hdn.getMaNV(), tenncc, hdn.getTenLaiXe(), hdn.getSDTLaiXe(), hdn.getNgayNhap()});
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu");
        }
    }

    private void editDanhSachHDN() {
        int maHDN = (int) tblDanhSachHDN.getValueAt(row, 0);
        int i = 1;
        try {

            HoaDonNhap hdn = daoHDN.selectByIdd(maHDN);
            setFormTO(hdn);
            tabs.setSelectedIndex(0);
            updateStatus();

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void fillDSHoaDonChiTiet() {
        DefaultTableModel model = (DefaultTableModel) tblMatHang.getModel();
        model.setRowCount(0);
        int i = 1;
        double ttienHDN = 0;
        listHDCT = daoHDNCT.selectByIdd(Integer.parseInt(txtMaHDN.getText()));
        for (HoaDonNhapChiTiet hd : listHDCT) {
            model.addRow(new Object[]{i++, hd.getMaMH(), hd.getTenMH(), hd.getDVT(), hd.getSoLuong(), (hd.getGiaNiemYet()), doiTien(hd.getSoLuong() * hd.getGiaNiemYet()), hd.getGhiChu()});
            ttienHDN += (hd.getSoLuong() * hd.getGiaNiemYet());
        }
        lblTongTienHDN.setText(doiTien(ttienHDN));
    }

    private void updateStatus() {
        boolean edit = (this.row >= 0);
        //Trạng thái form
        txtTenNV.setEditable(!edit);
        txtMaHDN.setEditable(!edit);
        btnThemHD.setEnabled(!edit);
        btnSuaHD.setEnabled(edit);
        // btnXoa.setEnabled(edit);
    }

    void clearForm() {
        NhanVien nv = daonv.selectByTenNV(Auth.user.getMaNV());
        String tennv = nv.getTenNV();
        txtMaHDN.setText(String.valueOf(Integer.parseInt(String.valueOf(daoHDN.MaxMaHDN())) + 1));
        txtNgayNhap.setEditable(false);
        txtTenNV.setEditable(false);
        txtNgayNhap.setText(XDate.toString2(XDate.now(), "yyyy-MM-dd"));
        txtTenNV.setText(tennv);
        cboTenNCC.setSelectedIndex(0);
        btnThemHD.setEnabled(true);
        txtMaHDN.setEditable(false);
        txtTenLxe.setText("");
        txtSDTLxe.setText("");
        DefaultTableModel model = (DefaultTableModel) tblMatHang.getModel();
        model.setRowCount(0);
        clearMatHangMoi();
        listHDCT.clear();
    }

    void fillCboKho() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboKho.getModel();
        model.removeAllElements();
        List<Kho> list = daoKho.selectAll();
        for (Kho k : list) {
            model.addElement(k);
        }

    }

    void fillCboTenNCC() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboTenNCC.getModel();
        model.removeAllElements();
        List<NhaCungCap> list = daoNCC.selectAll();

        for (NhaCungCap ncc : list) {
            model.addElement(ncc);
        }

    }

    void fillNCC() {
        String a = cboTenNCC.getSelectedItem() + "";
        NhaCungCap ncc = (NhaCungCap) daoNCC.selectBySDTNCC(a);
        String sdt = ncc.getSDT();
        String DiaChi = ncc.getDiaChi();
        txtSDTNCC.setText(sdt);
        txtDiaChiNCC.setText(DiaChi);
    }

    private void fillCboMatHang() {
        Kho k1 = new Kho();
        if (cboKho.getItemCount() != 0) {
            if (cboKho.getSelectedIndex() != -1) {
                k1 = (Kho) cboKho.getSelectedItem();
            } else {
                return;
            }
        } else {
            return;
        }
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboTenMatHang.getModel();
        model.removeAllElements();
        List<MatHang> list = daoMatHang.selectByMaKho(k1.getMaKho());
        for (MatHang mh : list) {
            model.addElement(mh);
        }
    }

    void fillCboDVT() {
        MatHang mh = new MatHang();
        if (cboTenMatHang.getItemCount() != 0) {
            if (cboTenMatHang.getSelectedIndex() != -1) {
                mh = (MatHang) cboTenMatHang.getSelectedItem();
            } else {
                return;
            }
        } else {
            return;
        }

        lblDVT.setText(mh.getDonVi());

    }

    private void clearMatHangMoi() {
        cboKho.setSelectedIndex(0);
        cboTenMatHang.setSelectedIndex(0);
        txtGia.setText("");
        txtSoLuong.setText("");
        txtGhiChu.setText("");
    }

    HoaDonNhapChiTiet getFormHDNCCT() {

        MatHang mh2 = daoMatHang.selectMaMH(cboTenMatHang.getSelectedItem() + "");
        String mamh = mh2.getMaMH();
        HoaDonNhapChiTiet hdct = new HoaDonNhapChiTiet();
        hdct.setTenMH(cboTenMatHang.getSelectedItem() + "");
        hdct.setDVT(lblDVT.getText());
        hdct.setGhiChu(txtGhiChu.getText());
        hdct.setGiaNiemYet(Double.parseDouble(txtGia.getText()));
        hdct.setMaHDN(Integer.parseInt(txtMaHDN.getText()));
        hdct.setMaMH(mamh);

        hdct.setSoLuong(Double.parseDouble(txtSoLuong.getText()));
        return hdct;
    }

    private void InsertMatHang() {

        HoaDonNhapChiTiet hdct = getFormHDNCCT();
        listHDCT.add(hdct);
        fillTableMatHang();
    }

    private void InsertMatHang2() {

        HoaDonNhapChiTiet hdct = getFormHDNCCT();
        listCT.add(hdct);
        fillTableMatHang2();
    }

    private void updateMatHang() {
        String err = checkCT("Sua");
        if (err.equals("")) {
            row = tblMatHang.getSelectedRow();
            HoaDonNhapChiTiet mh = listHDCT.get(row);
            MatHang mh2 = daoMatHang.selectMaMH(cboTenMatHang.getSelectedItem() + "");
            String mamh = mh2.getMaMH();
            mh.setMaHDN(Integer.parseInt(txtMaHDN.getText()));
            mh.setMaMH(mamh);
            mh.setTenMH(cboTenMatHang.getSelectedItem() + "");
            mh.setDVT(lblDVT.getText());
            mh.setSoLuong(Double.parseDouble(txtSoLuong.getText()));
            mh.setGiaNiemYet(Double.parseDouble(txtGia.getText()));
            mh.setGhiChu(txtGhiChu.getText());
            HoaDonNhap hdn = daoHDN.selectById(txtMaHDN.getText());
            if (hdn != null) {
                daoHDNCT.update(mh);
                updateSLMatHang(daoMatHang.selectById(mh.getMaMH()));
            }
            fillTableMatHang();
        } else {
            MsgBox.alert(this, err);
        }
    }

    private void deleteMatHang() {
//        row = tblMatHang.getSelectedRow();
//        HoaDonNhapChiTiet mh = listHDCT.get(row);
//        listHDCT.remove(row);
//        //daoHDNCT.delete(mh.getID());
//        fillTableMatHang1();
        HoaDonNhap hd = daoHDN.selectByIdd(Integer.parseInt(txtMaHDN.getText()));
        int r = tblMatHang.getSelectedRow();
        if (r >= 0) {
            if (hd != null) {
                int hdct = listHDCT.get(r).getID();
                daoHDNCT.delete2(hdct);
                updateSLMatHang(daoMatHang.selectById(listHDCT.get(r).getMaMH()));
            }
            listHDCT.remove(r);
            fillTableMatHang();
        } else {
            MsgBox.alert(this, "Chưa chọn mặt hàng để xóa");
        }
    }

    void fillTableMatHang() {
        int i = 1;
        double ttienHDN = 0;
        DefaultTableModel model = (DefaultTableModel) tblMatHang.getModel();
        model.setRowCount(0);
        for (HoaDonNhapChiTiet mh : listHDCT) {
            model.addRow(new Object[]{i++, mh.getMaMH(), mh.getTenMH(), mh.getDVT(), mh.getSoLuong(), (mh.getGiaNiemYet()), doiTien(mh.getGiaNiemYet() * mh.getSoLuong()), mh.getGhiChu()});
            ttienHDN += (mh.getSoLuong() * mh.getGiaNiemYet());
        }
        lblTongTienHDN.setText(doiTien(ttienHDN));
    }

    void fillTableMatHang2() {
        double ttienHDN = 0;

        int i = 1;
        DefaultTableModel model = (DefaultTableModel) tblMatHang.getModel();
        model.setRowCount(0);
        for (HoaDonNhapChiTiet mh : listCT) {
            model.addRow(new Object[]{i++, mh.getMaMH(), mh.getTenMH(), mh.getDVT(), mh.getSoLuong(), (mh.getGiaNiemYet()), doiTien(mh.getGiaNiemYet() * mh.getSoLuong()), mh.getGhiChu()});
            ttienHDN += (mh.getSoLuong() * mh.getGiaNiemYet());
        }
        lblTongTienHDN.setText(doiTien(ttienHDN));
    }

    void fillTableMatHang1() {
        int i = 1;
        double ttienHDN = 0;

        DefaultTableModel model = (DefaultTableModel) tblMatHang.getModel();
        listHDCT = (List<HoaDonNhapChiTiet>) daoHDNCT.selectByIdd(Integer.parseInt(txtMaHDN.getText()));
        model.setRowCount(0);
        if (listHDCT.isEmpty()) {
            MsgBox.alert(this, "Không còn dữ liệu");
        } else {
            for (HoaDonNhapChiTiet mh : listHDCT) {
                ttienHDN += (mh.getSoLuong() * mh.getGiaNiemYet());
                model.addRow(new Object[]{i++, mh.getMaMH(), mh.getTenMH(), mh.getDVT(), mh.getSoLuong(), (mh.getGiaNiemYet()), doiTien(mh.getGiaNiemYet() * mh.getSoLuong()), mh.getGhiChu()});
            }
        }
        lblTongTienHDN.setText(doiTien(ttienHDN));
    }

    private void editMatHang() {
        row = tblMatHang.getSelectedRow();
        HoaDonNhapChiTiet mh = listHDCT.get(row);
        cboTenMatHang.setSelectedItem(mh.getTenMH());
        lblDVT.setText(mh.getDVT());
        txtGia.setText(mh.getGiaNiemYet() + "");
        txtSoLuong.setText(mh.getSoLuong() + "");
        Kho k = daoKho.selectByTENKHO(mh.getTenMH());

        cboKho.setSelectedItem(k);
        txtGhiChu.setText(mh.getGhiChu());
    }

    private void fillCboMaHD() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboLocTheoMaHD.getModel();
        model.removeAllElements();
        List<HoaDonNhap> listMaHD = daoHDN.selectAll();
        model.addElement("...");
        for (HoaDonNhap hoaDonNhap : listMaHD) {
            int mahd = hoaDonNhap.getMaHDN();
            model.addElement(mahd);
        }
    }

    private void fillTableTheoMaHD() {
        DefaultTableModel model = (DefaultTableModel) tblDanhSachHDN.getModel();
        model.setRowCount(0);
        try {
            int mahd = (int) cboLocTheoMaHD.getSelectedItem();
            HoaDonNhap lst = daoHDN.selectByIdd(mahd);
            model.addRow(new Object[]{lst.getMaHDN(), lst.getMaNV(), lst.getMaNCC(), lst.getTenLaiXe(), lst.getSDTLaiXe(), lst.getNgayNhap()});
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private File createNewFile() {
        String date = XDate.toString(XDate.now(), "yyyy-MM-dd");
        String fn = "HDN_" + txtMaHDN.getText() + "_" + date + ".xlsx";
        File excelExport = new File("C:\\Users\\ADMIN\\Desktop\\ReportHDN\\" + fn);
        File exportEx = new File("C:\\Users\\ADMIN\\Desktop\\ReportHDN\\ExportMau.xlsx");
        try {
            WFile.copyFile(exportEx, excelExport);
            return excelExport;
        } catch (IOException ex) {
            throw new RuntimeException();
        }
    }

    private void ExportExcel(File file) {
        FileOutputStream fos = null;
        BufferedOutputStream bou = null;
        XSSFWorkbook excelJtableExport = null;
        DefaultTableModel model = (DefaultTableModel) tblMatHang.getModel();
        try {
            XSSFRow excelRow;
            XSSFCell excelCell = null;
            try {
                excelJtableExport = new XSSFWorkbook(file);
            } catch (InvalidFormatException ex) {
                ex.printStackTrace();
            }

            XSSFSheet excelSheet = excelJtableExport.getSheet("Sheet1");
            excelRow = excelSheet.createRow(10);
            Cell cel = excelRow.createCell(0);
            cel.setCellValue("STT");
            cel = excelRow.createCell(1);
            cel.setCellValue("Mã MH");
            cel = excelRow.createCell(2);
            cel.setCellValue("Tên mặt hàng");
            cel = excelRow.createCell(3);
            cel.setCellValue("DVT");
            cel = excelRow.createCell(4);
            cel.setCellValue("Số lượng");
            cel = excelRow.createCell(5);
            cel.setCellValue("Giá");
            cel = excelRow.createCell(6);
            cel.setCellValue("Thành tiền");
            cel = excelRow.createCell(7);
            cel.setCellValue("Ghi chú");

            for (int i = 0; i < model.getRowCount(); i++) {
                int currentRow = i + 11;
                excelRow = excelSheet.createRow(currentRow);
                for (int j = 0; j < model.getColumnCount(); j++) {
                    excelCell = excelRow.createCell(j);
                    excelCell.setCellValue(model.getValueAt(i, j).toString());
                }
            }

            excelRow = excelSheet.getRow(4);
            excelCell = excelRow.createCell(2);
            excelCell.setCellValue(txtMaHDN.getText());

            excelCell = excelRow.createCell(7);
            excelCell.setCellValue(txtNgayNhap.getText());

            excelRow = excelSheet.getRow(5);
            excelCell = excelRow.createCell(2);
            excelCell.setCellValue(txtTenNV.getText());

            excelRow = excelSheet.getRow(6);
            excelCell = excelRow.createCell(2);
            excelCell.setCellValue(String.valueOf(cboTenNCC.getSelectedItem()));

            excelRow = excelSheet.getRow(7);
            excelCell = excelRow.createCell(2);
            excelCell.setCellValue(txtSDTNCC.getText());

            excelRow = excelSheet.getRow(8);
            excelCell = excelRow.createCell(2);
            excelCell.setCellValue(txtDiaChiNCC.getText());

            excelRow = excelSheet.createRow(model.getRowCount() + 12);
            excelCell = excelRow.createCell(5);
            excelCell.setCellValue("Tổng tiền");
            excelCell = excelRow.createCell(6);
            excelCell.setCellValue(lblTongTienHDN.getText());
            fos = new FileOutputStream(file.getName());
            bou = new BufferedOutputStream(fos);
            excelJtableExport.write(bou);

            MsgBox.alert(this, "Export ok");
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            Logger.getLogger(HoaDonNhap.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                if (bou != null) {
                    bou.close();
                }
                if (fos != null) {
                    fos.close();
                }
                if (excelJtableExport != null) {
                    excelJtableExport.close();
                }

            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }

    }

    private void importExcel() {
        DefaultTableModel model = (DefaultTableModel) tblMatHang.getModel();
        model.setRowCount(0);

        FileInputStream excelFIS = null;
        BufferedInputStream excelBIS = null;
        XSSFWorkbook excelImportWoorkBook = null;

        String currentDirectoryPath = "C:\\Users\\ADMIN\\Desktop";
        JFileChooser excelfileImport = new JFileChooser(currentDirectoryPath);

        FileNameExtensionFilter excelFilter = new FileNameExtensionFilter("EXCEL FILES", "xls", "xlsx", "xslm");
        excelfileImport.setFileFilter(excelFilter);
        int excelChooser = excelfileImport.showOpenDialog(this);
        if (excelChooser == JFileChooser.APPROVE_OPTION) {

            try {
                File excelFile = excelfileImport.getSelectedFile();
                excelFIS = new FileInputStream(excelFile);
                excelBIS = new BufferedInputStream(excelFIS);
                excelImportWoorkBook = new XSSFWorkbook(excelBIS);
                XSSFSheet excelSheet = excelImportWoorkBook.getSheetAt(0);

                for (int i = 11; i < excelSheet.getLastRowNum() - 1; i++) {
                    XSSFRow excelRow = excelSheet.getRow(i);
                    XSSFCell cell0 = excelRow.getCell(0);
                    XSSFCell cell1 = excelRow.getCell(1);
                    XSSFCell cell2 = excelRow.getCell(2);
                    XSSFCell cell3 = excelRow.getCell(3);
                    XSSFCell cell4 = excelRow.getCell(4);
                    XSSFCell cell5 = excelRow.getCell(5);
                    XSSFCell cell6 = excelRow.getCell(6);
                    XSSFCell cell7 = excelRow.getCell(7);
                    String MaMH = cell1 + "";
                    String TenMH = cell2 + "";
                    String DVT = cell3 + "";
                    double SL = Double.parseDouble(cell4 + "");
                    double gia = Double.parseDouble(cell5 + "");
                    String ghiChu = cell6 + "";
                    HoaDonNhapChiTiet hdct = new HoaDonNhapChiTiet();
                    hdct.setMaHDN(Integer.parseInt(txtMaHDN.getText()));
                    hdct.setMaMH(MaMH);
                    hdct.setTenMH(TenMH);
                    hdct.setDVT(DVT);
                    hdct.setSoLuong(SL);
                    hdct.setGiaNiemYet(gia);
                    hdct.setGhiChu(ghiChu);
                    listHDCT.add(hdct);

                    model.addRow(new Object[]{cell0, cell1, cell2, cell3, cell4, cell5, cell6, cell7});
                }

                MsgBox.alert(this, "Import thành công");
            } catch (FileNotFoundException ex) {
                ex.printStackTrace();
                // Logger.getLogger(ImportDataExcel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }

    }

    private void timHDNTheoNgay() {
        String ktDate = "^\\d{4}-\\d{2}-\\d{2}$";
        String dateText = txtTimTheoNgay.getText();
        if (!dateText.matches(ktDate)) {
            MsgBox.alert(this, "Nhập sai định dạng ngày (yyyy-mm-dd)");
        } else {
            DefaultTableModel model = (DefaultTableModel) tblDanhSachHDN.getModel();
            model.setRowCount(0);
            java.util.Date utilDate = XDate.toDate(txtTimTheoNgay.getText(), "yyyy-MM-dd");
            Date a = new java.sql.Date(utilDate.getTime());

            List<HoaDonNhap> list = daoHDN.selectByNgayNhap(a);
            for (HoaDonNhap nn : list) {
                model.addRow(new Object[]{nn.getMaHDN(), nn.getMaNV(), nn.getMaNCC(), nn.getTenLaiXe(), nn.getSDTLaiXe(), nn.getNgayNhap()});
            }
        }
    }

//    private void TongSLMatHang() {
//        String mamh = "";
//        List<HoaDonNhapChiTiet> hdct = daoHDNCT.selectAll();
//        List<MatHang> listmh = daoMatHang.selectAll();
//        for (HoaDonNhapChiTiet hoaDonNhapChiTiet : hdct) {
//            String MaMH = hoaDonNhapChiTiet.getMaMH();
//            for (MatHang matHang : listmh) {
//                mamh = matHang.getMaMH();
//                if (MaMH.equalsIgnoreCase(mamh)) {
//                    List<HoaDonNhapChiTiet> listsl = daoHDNCT.selectBySL(MaMH);
//                    double tongsl = 0;
//                    for (HoaDonNhapChiTiet hd : listsl) {
//                        tongsl = tongsl + hd.getSoLuong();
//                    }
//                    matHang.setSoLuong(tongsl);
//                    daoMatHang.update2(matHang);
//                }
//            }
//
//        }
//
//    }
    
    private void updateSLMatHang(MatHang mh) {
        HoaDonNhap hdn = daoHDN.selectById(txtMaHDN.getText());
        if (hdn != null) {
            mh.setSoLuong(daoMatHang.selectTongMH(mh.getMaMH()));
            daoMatHang.updateSL(mh);
        }
    }

    private String doiTien(Object ob) {
        DecimalFormat fm = new DecimalFormat("#");
        Locale localeVN = new Locale("vi", "VN");
        NumberFormat currencyVN = NumberFormat.getCurrencyInstance(localeVN);
        return currencyVN.format(Double.parseDouble(String.valueOf(ob)));
    }

    private String check(String btn) {
        String err = "";
        if (CheckData.isNull(txtTenLxe.getText())) {
            err += "Tên lái xe không để trống\n";
        }
        if (CheckData.isNull(txtSDTLxe.getText())) {
            err += "SĐT không được để trống\n";
        } else {
            if (!CheckData.sdt(txtSDTLxe.getText())) {
                err += "SĐT sai định dạng\n";
            }
        }
        return err;
    }

    private String checkCT(String btn) {
        String err = "";
        if (CheckData.isNull(txtSoLuong.getText())) {
            err += "Số lượng không được để trống\n";
        }
        if (!CheckData.isDouble(txtSoLuong.getText())) {
            err += "Số lượng sai định dạng\n";
        }
        if (CheckData.isNull(txtGia.getText())) {
            err += "Giá không được để trống\n";
        } else {
            if (!CheckData.isDouble(txtGia.getText())) {
                err += "Giá sai định dạng\n";
            }
        }
        return err;
    }

}
